INSERT INTO USER (ID, USERNAME, PASSWORD, NAME, PERSONID, ENABLED, LASTPASSWORDRESETDATE) VALUES (1, 'araut', '$2a$10$P6J./61LYCo0DhYqDYrDzuUgo.sKGGXvDpuIiJzFckD6eMN6sGgZK', 'Ashish', '1', 1, PARSEDATETIME('21-03-2019', 'dd-MM-yyyy'));

INSERT INTO USER (ID, USERNAME, PASSWORD, NAME, PERSONID, ENABLED, LASTPASSWORDRESETDATE) VALUES (2, 'jsmith', '$2a$10$1c.Qpqa4ci8p.sUhVoarW.UbIn0kTXjMi.TCU.16m/U2f/sYR87A6', 'John', '1', 2, PARSEDATETIME('21-03-2019', 'dd-MM-yyyy'));

INSERT INTO PERSON (ID, FIRSTNAME, LASTNAME, EMAIL, PHONE) VALUES (1, 'Ashish', 'Raut', 'ashish@gmail.com', '5168033202');

INSERT INTO PERSON (ID, FIRSTNAME, LASTNAME, EMAIL, PHONE) VALUES (2, 'John', 'Smith', 'jsmith@gmail.com', '2123147566');

